### ISSUE TITLE
QErrorMessage argument type bug

### ISSUE THREAD

**Issue by PierreRochard** [lightning-power-users/node-launcher#144]
![image](https://user-images.githubusercontent.com/6299681/51921309-23e87380-23b5-11e9-920a-3200601823ad.png)

**Comment by BobleChinois** [comment]
Hi Pierre, can I have some more details about the issue to see if I can tackle it?
I'm a bit puzzled by the `nullptr`, after doing a quick search it seems that it is used in C++ for a pointer that points to a variable whose value is NULL. 
My understanding is that line 103 should be written `QErrorMessage.showMessage(details)`, and not `QErrorMessage(self).showMessage(details)`. I made a quick research in the node-launcher repo and other repos, and I didn't find occurrences of `QErrorMessage(self).showMessage(x)`, am I missing something?

**Comment by PierreRochard** [comment]
The library we're using (pyside2) is a very thin wrapper around a C++ library, so you're absolutely right

Your solution looks perfect!

**Comment by BobleChinois** [comment]
Ok, can you give a bit more details about how to reproduce the bug, so that I can test the fix? Thanks!

**Comment by PierreRochard** [comment]
Bug reproduction: https://github.com/PierreRochard/node-launcher/commit/77fcbcdc5ba8852637f4499ef84191e42dcbe5b1

Suggested bug fix (imo needs more research so we understand why, but it worked for me): https://github.com/PierreRochard/node-launcher/commit/6bacd1e5b4682d5a819d484c110b2004ae996226

Here's a test that checks that the showMessage class method gets called instead of the instance method: https://github.com/PierreRochard/node-launcher/commit/9e5f48e852274cdc55ed0cff6dfebea5b03a3f17

**Comment by BobleChinois** [comment]
Can I have more details about how to reproduce the bug? I build the `77fcbcd` commit and start to play with LND, but I couldn't raise the error I was looking for. I see it is in a `lnd_poll` function, but I'm not sure what it is about, nor how to raise this exception. 

Since it tries `unlock(password)`, is it supposed to raise exception if I try to launch LND and unlock wallet with a false password? Since unlocking is automated I don't even have an idea how to do that.

**Comment by BobleChinois** [comment]
Hi, I spend some more time reading doc and playing around, I have another fix that works as good as the one you proposed, I don't know which one is better though : https://github.com/BobleChinois/node-launcher/commit/6bc50b5c55a5a8fafefad2f021d28e47e2083a09
My understanding is that since we declared `self.error_message = QErrorMessage()` in the `__init__` function of the class, we need to call `self.error_message` and not `QErrorMessage()` which is the class itself and not an instantiation of the class. 
That's why `QErrorMessage.showMessage(self.error_message, details)` works too, it is just calling the instance inside the `showMessage` function call. 
Does it make sense or am I missing something obvious?

**Comment by BobleChinois** [comment]
Submitted PR https://github.com/lightning-power-users/node-launcher/pull/153
