### ISSUE TITLE
Lnd.conf tweaks for better RTL integration

### ISSUE THREAD

**Issue by saubyk** [lightning-power-users/node-launcher#223]
* **I'm submitting a ...**
  - [x] feature request

The 'lnd.conf' which is generated by node launcher, causes integration failures for the REST APIs.

the following parameter values in the lnd.conf should address the problem:
`restlisten=0.0.0.0:8080`
`rpclisten=0.0.0.0:10009`
`tlsextraip=0.0.0.0`

**Comment by PierreRochard** [comment]
What's the security impact?

**Comment by saubyk** [comment]
@PierreRochard based on my research so far, not a significant impact.

Will work on it a bit more and revert. Thanks.

**Comment by JeffVandrewJr** [comment]
@saubyk @PierreRochard While unlikely, listening on `0.0.0.0` could be a problem if a user has no firewall. We use `0.0.0.0` for listening with BTCPay, but that's because Docker container ports aren't accessible to the outside world unless the container specifically exposes them. On a local machine, it's a potentially different issue.

Couldn't this be used instead?
```
restlisten=127.0.0.1:8080
rpclisten=127.0.0.1:10009
tlsextraip=127.0.0.1
```
The above _should_ expose all the ports to RTL assuming RTL resides on the machine as lnd, but without listening for outside connections to the REST API.

**Comment by saubyk** [comment]
@PierreRochard  @JeffVandrewJr 

Testing with these settings. This works and exposes the ports much less. Thanks, as always @JeffVandrewJr  :-)

Although this setting will work if RTL and LND are running on the same machine, which should be the most common use case.

```
restlisten=127.0.0.1:8080
rpclisten=127.0.0.1:10009
tlsextraip=127.0.0.1
```

**Comment by PierreRochard** [comment]
Great, and I'm assuming the TLS cert needs to be deleted and recreated by LND for this to work properly? I can definitely have the Node Launcher automatically do that!

**Comment by saubyk** [comment]
I just updated the settings from `0.0.0.0` to `127.0.0.1` and restarted LND, without deleting tls certs and it worked.
But it may be safe to delete the certs, to remove the doubt.

**Comment by PierreRochard** [comment]
Turns out `restlisten` and `rpclisten` are already defaulting to the proposed values and RTL works great with those existing defaults. I've added a default for `tlsextraip` since that can't hurt.

**Comment by saubyk** [comment]
Thanks Pierre.
Adding `tlsextraip` should help for the seamless execution of RTL, upon install.

**Comment by PierreRochard** [comment]
I didn't notice any difference with adding `tlsextraip`, so people may still have problems! We'll see
