### ISSUE TITLE
Can i still use the bitcoin core GUI when node is running?

### ISSUE THREAD

**Issue by HurlyDesousa** [lightning-power-users/node-launcher#258]
* **I'm submitting a ...**
  - [ ] support request
Can i still use the bitcoin core GUI when node is running?

My node is fully synced. But when i open the Bitcoin Core wallet i get this error.

![image](https://user-images.githubusercontent.com/34354667/55754568-3df5a080-5a4d-11e9-87e1-0b6a4aa484bc.png)

**Comment by PierreRochard** [comment]
Nope, you can't :(

Are you using it as a wallet? Or did you just want to see stats about the node?

**Comment by HurlyDesousa** [comment]
Thanks for your response.

I thought the node would have a bitcoin wallet integrated. 

How do i use a bitcoin wallet then, do i first need to switch of the node software every time i open the my bitcoin wallet?

**Comment by PierreRochard** [comment]
LND had an on-chain Bitcoin wallet built into it.

I disabled the Bitcoin Core wallet for the Node Launcher to avoid people accidentally sending coins to it instead of LND. 

I would recommend sweeping the coins from your Bitcoin Core wallet to your LND wallet. If it’s a lot of coins, I don’t think either wallet is the appropriate solution
