### ISSUE TITLE
Wild bug appears! 

### ISSUE THREAD

**Issue by watwood** [lightning-power-users/node-launcher#270]
* **I'm submitting a ...**
  - [ 1] bug report

* **What is the current behavior?**
I get this error message:

Wild bug appears! 

Error information:

'LndOutputWidget' object has no attribute 'error_message'
File "node_launcher/gui/system_tray_widgets/lnd_output_widget.py", line 151, in handle_unlock_wallet File "node_launcher/gui/system_tray_widgets/lnd_output_widget.py", line 103, in generate_seed 

* **If the current behavior is a bug, please provide the steps to reproduce**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

  - Operating System: [ Windows | macOS | Linux ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by PierreRochard** [comment]
Fixed by https://github.com/lightning-power-users/node-launcher/commit/216c8a8a48857f786d438a09ab627b1a2356ef4f

Now that the bug in the error message is fixed, hopefully we'll see what the error message was!

Thanks for reporting, let me know if the latest release has any issues or you have a feature request!

Cheers
