### ISSUE TITLE
Node Launcher not launching in latest MacOS

### ISSUE THREAD

**Issue by 2bit1** [lightning-power-users/node-launcher#480]
* **I'm submitting a ...**
  - [ ] bug report

* **What is the current behavior?**

Wild bug appears! 
Please copy this text and open an issue on GitHub.
Node Launcher version 6.0.6

Error information:

file could not be opened successfully
File "run.py", line 22, in File "node_launcher/gui/application.py", line 15, in __init__ File "node_launcher/node_set/node_set.py", line 41, in __init__ File "node_launcher/node_set/lnd.py", line 90, in __init__ File "node_launcher/services/lnd_software.py", line 15, in lnd File "node_launcher/services/node_software.py", line 73, in executable_path File "node_launcher/services/node_software.py", line 92, in extract File "tarfile.py", line 1578, in open 

* **Please tell us about your environment:**

  - Operating System: macOS

**Comment by Dar1Theory** [comment]
Same as #479

**Comment by 2bit1** [comment]
Doea Umbrel work with MacOS? Hearing that we would be able to run a full node on Zap Desktop soon as well?

**Comment by Dar1Theory** [comment]
Nope. 

Raspberry PI 4 or create a standalone linux box. Yes, you can do that on a USB then boot it as a VM under MacOS. 

The easier way is definitely PI. There are many, many tutorials that show it all, including parts lists, putting it together, Installing the OS, installing all the software. 

Have a look here: https://getumbrel.com/

Darwin

Doea Umbrel work with MacOS? Hearing that we would be able to run a full node on Zap Desktop soon as well?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PierreRochard** [comment]
Hi @2bit1 and @Dar1Theory , please try the new release: https://github.com/lightning-power-users/node-launcher/releases/

**Comment by Dar1Theory** [comment]
Thanks! I’ll try it.

 

Hi @2bit1 and @Dar1Theory , please try the new release: https://github.com/lightning-power-users/node-launcher/releases/

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Dar1Theory** [comment]
Thanks! Sorry it’s taken so long. 

It’s up and running. Thank you for doing the update. I’m running 11.5.1 and it’s great so far. 

Darwin

 

Hi @2bit1 and @Dar1Theory , please try the new release: https://github.com/lightning-power-users/node-launcher/releases/

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PierreRochard** [comment]
Great, congratulations!
